"""initial migration

Revision ID: 4837ef55f2af
Revises: 
Create Date: 2025-12-22 13:36:54.925681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4837ef55f2af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pdf_filename', sa.String(length=500), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=False),
    sa.Column('output_filename', sa.String(length=500), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=200), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('diagrams_detected', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_expires_at', 'jobs', ['expires_at'], unique=False)
    op.create_index('idx_status', 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_expires_at'), 'jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_expires_at'), table_name='jobs')
    op.drop_index('idx_status', table_name='jobs')
    op.drop_index('idx_expires_at', table_name='jobs')
    op.drop_index('idx_created_at', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
